# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: pwd
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      if: always()
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install --force
    - run: CI=false npm run build --if-present
      if: always()
    
    - name: FTP Deploy
      if: always()
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # ftp server
        server: h22.seohost.pl
        # ftp username
        username: Githubuser45036@srv45036.seohost.com.pl
        # ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftps
        # Folder to upload from, must end with trailing slash /
        local-dir: ./build/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: /public_html/
        # Path and name of the state file - this file is used to track which files have been deployed
        exclude: |
          **/cgi-bin*
